### ISSUE TITLE
Add a total for countvm-host  mode

### ISSUE THREAD

**Issue by garnier-quentin** [centreon/centreon-vmware#23]
It's by ESX. Should also have a total.

**Comment by Hellnino18** [comment]
Hi, I'm testing centreon-vmware and it works very well. But I need this enhancement too.... Because we have 15 ESX on 1 Vsphere server, and 15 x 3 metrics si too big (I know we could filter perfdata). But I would love to have a total by Cluster or by Vcenter directly.

Thanks in advance for your help !
