### ISSUE TITLE
[2.3.0] - unable to check memory/network ESX host

### ISSUE THREAD

**Issue by tpaxle** [centreon/centreon-vmware#31]
###Packages
ces-plugins-Virtualization-VMWare-client-2.3.0-1.el6.noarch
ces-plugins-Virtualization-VMWare-daemon-2.3.0-1.el6.noarch

Hi.

I'm not able to configure checks of memory and Network traffic of ESX. However, others check run ok:

[]# /etc/centreon-scripts/centreon-plugins/centreon_plugins.pl --plugin apps::vmware::connector::plugin --custommode=connector --connector-hostname=127.0.0.1 --container=ESXi5 --mode  time-host --esx-hostname <hostnameesx>
OK: '<hostnameesx>' Time offset 0 second(s) : 2016-11-03T13:06:17.999873Z | 'offset'=-0.999872922897339s;;;0;

[]# /etc/centreon-scripts/centreon-plugins/centreon_plugins.pl --plugin apps::vmware::connector::plugin --custommode=connector --connector-hostname=127.0.0.1 --container=ESXi5 --mode  net-host --esx-hostname <hostnameesx> --sampling-period 20
UNKNOWN: Cannot get value for counters (Maybe, object(s) cannot be reached: disconnected, not running, time not synced (see time-host mode),...) |

[]# /etc/centreon-scripts//centreon-plugins/centreon_plugins.pl --plugin apps::vmware::connector::plugin --custommode=connector --connector-hostname=127.0.0.1 --container=ESXi5 --mode  net-host --esx-hostname <hostnameesx>
UNKNOWN: Cannot get counter 'net.received.average' for the sampling period '300' (counter level: 2, sampling level: 1) |

[]#/etc/centreon-scripts/centreon-plugins/centreon_plugins.pl --plugin apps::vmware::connector::plugin --custommode=connector --connector-hostname=127.0.0.1 --container=ESXi5 --mode  cpu-host --esx-hostname <hostnameesx>
OK: '<hostnameesx>' Total Average CPU usage '55.66%' on last 5 min | 'cpu_total'=55.66%;;;0;100 'cpu_total_MHz'=10687.00MHz;;;0;19200 'cpu0'=30.76%;;;0;100 'cpu1'=28.08%;;;0;100 'cpu2'=32.07%;;;0;100 'cpu3'=27.41%;;;0;100 'cpu4'=29.13%;;;0;100 'cpu5'=31.26%;;;0;100 'cpu6'=29.62%;;;0;100 'cpu7'=31.21%;;;0;100 'cpu8'=26.92%;;;0;100 'cpu9'=24.57%;;;0;100 'cpu10'=26.61%;;;0;100 'cpu11'=24.74%;;;0;100 'cpu12'=26.43%;;;0;100 'cpu13'=24.81%;;;0;100 'cpu14'=26.60%;;;0;100 'cpu15'=24.96%;;;0;100

On the other hand, With another plugins... there aren't Issues:
[]# ./check_vmware_api -D <VCENTER> -u <uservcenter> -p <passvcenter> -H <hostnameesx> -l mem -s usage
CHECK_VMWARE_API OK - mem usage=83.83 % | mem_usage=83.83%;;

**Comment by garnier-quentin** [comment]
For the following error:
```
UNKNOWN: Cannot get counter 'net.received.average' for the sampling period '300' (counter level: 2, sampling level: 1) |
```

VCenter has a configuration to get counters from ESX Servers:
- for sampling period 'Past Day', by default the level is 1
- Some counters like 'mem.state.latest' and 'net.received.average' need a configuration to 2 for the level.

With the configuration at 1, vcenter doesn't get statistics from ESX. From VMWare documentation:

The interval level corresponds to the performance counter level (PerfCounterInfo.level). The Server will collect data for all counters with levels that match PerfInterval.level, and for all counters with levels lower than PerfInterval.level. You can modify this property on a vCenter Server only.

In our case 2 is greater than 1.

The configuration can be changed in the vcenter: Administration-> VCENTER Settings-> STATISTICS

After the change in the vcenter, the centreon_vmware needs to be restarted (and wait a little time).

For the memory, it's the same. Because memory gets the memory state counter.

**Comment by tpaxle** [comment]
Thanks @garnier-quentin. With this configuration in the vcenter all work!
